### PR TITLE
Add support for JAAS

### PR DESCRIPTION
**Pull request by johnsca**
JAAS will always be available as a controller, so the Controller Picker screen will always be shown.  If you have not logged in to JAAS before, you will be prompted for login credentials.  You will then be prompted to choose a supported cloud (aws, gce, azure), and the model will be created there and deployment will proceed as usual.

Edit: To see the JAAS login and registration form again, you will need to do two things:
* `juju unregister jaas`
* `rm ~/.go-cookies ~/.local/share/juju/store-usso-token`

- [x] Always show Controller Picker with JaaS option
- [x] Prompt for JaaS / USSO credentials if not already present on system
- ~~Allow browser-based login option~~
- [x] Return to login form on failed login
- [x] Register JaaS controller after successfull login
- [x] Always prompt for cloud selection for JaaS
- [x] Add model for JaaS instead of bootstrap

From review:
- [x] Move Login button to footer
- [x] Hide "Configure a New Cloud" section if empty
- [x] Fix adding new cloud credentials flow in JaaS flow
- [ ] Debug error (`CONJURE_UP_SPELLSDIR`) on kubes bundle in JaaS flow
- [x] Remove "Waiting" from JaaS interstitials
- [ ] Verify KITT bar animation on all interstitials

### CODE REVIEW

**Comment by battlemidget** [comment]
Taking pictures as i go:

I like this, we probably want to pass this through design to see what they think about the wording and flow
image

The login button should be at the bottom right with the same style as the **QUIT** button
(I couldnt get the login view to show up again, once i can ill add a new screenshot here)

Remove the configure new cloud section
image

The next image should show the `deploystatus` view to list the applications, instead of, the "bootstrap" wait view
image

It ended with an error trying to find `CONJURE_UP_SPELLSDIR`
```
ubuntu@riddick:~/conjure-up-jaas$ cat ~/.cache/conjure-up/conjure-up.log
2017-03-20 14:17:06,933 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: LXD version: 2.11, Juju version: 2.2-beta1-xenial-amd64
2017-03-20 14:17:11,831 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Path is local filesystem, copying /snap/conjure-up/x1/spells/canonical-kubernetes to /home/ubuntu/.cache/conjure-up/canonical-kubernetes
2017-03-20 14:19:23,099 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Rendering bootstrap wait
2017-03-20 14:21:35,569 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: AddMachines: [{'series': 'xenial', 'constraints': {}, 'jobs': ['JobHostUnits']}]
2017-03-20 14:21:35,571 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: AddMachines: [{'series': 'xenial', 'constraints': {}, 'jobs': ['JobHostUnits']}]
2017-03-20 14:21:35,571 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Adding Charm cs:~containers/xenial/flannel-11
2017-03-20 14:21:35,572 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: AddMachines: [{'series': 'xenial', 'constraints': {}, 'jobs': ['JobHostUnits']}]
2017-03-20 14:21:35,573 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: AddMachines: [{'series': 'xenial', 'constraints': {}, 'jobs': ['JobHostUnits']}]
2017-03-20 14:21:35,573 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: AddMachines: [{'series': 'xenial', 'constraints': {}, 'jobs': ['JobHostUnits']}]
2017-03-20 14:21:35,574 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: AddRelation: {'Endpoints': ['kubernetes-master:certificates', 'easyrsa:client']}
2017-03-20 14:21:35,581 [ERROR] log.py:17 - conjure-up/_unspecified_spell: error running /home/ubuntu/.cache/conjure-up/canonical-kubernetes/steps/00_deploy-done:
b'/home/ubuntu/.cache/conjure-up/canonical-kubernetes/steps/00_deploy-done: line 10: CONJURE_UP_SPELLSDIR: unbound variable\n'
2017-03-20 14:21:35,582 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Showing dialog for exception: Error in waiting for deployment to finish: /home/ubuntu/.cache/conjure-up/canonical-kubernetes/steps/00_deploy-done: line 10: CONJURE_UP_SPELLSDIR: unbound variable
```

**Comment by johnsca** [comment]
> The next image should show the deploystatus view to list the applications, instead of, the "bootstrap" wait view

There are two places the interstitial should be shown in the JaaS workflow:
1) Between the USSO / JaaS login form and the choose cloud screen
2) After the deploy screen if Deploy All is selected before add-model is finished

The first one can't be avoided (i.e., it can't go directly to the deploy screen) because the cloud has to be chosen before going to deploy, and the login has to be confirmed before the cloud is chosen because it might have to go back to the form if the login info was entered incorrectly.  The second one should behave the same as if bootstrap wasn't finished.

If you're seeing the interstitial at any other time, then that's an issue.

**Comment by johnsca** [comment]
> It ended with an error trying to find CONJURE_UP_SPELLSDIR

I don't know where that error is coming from but I don't think it's related to this change.  I'll try to reproduce using canonical-kubernetes.

**Comment by battlemidget** [comment]
> The second one should behave the same as if bootstrap wasn't finished.
> 
> If you're seeing the interstitial at any other time, then that's an issue.

The view doesn't seem to be updated in a loop as the KITT bar seems stuck, and never progresses to the next screen in the flow.

**Comment by johnsca** [comment]
Task list:

- [x] Move Login button to footer
- [ ] Remove "Configure a New Cloud" section from cloud selection in JaaS flow
- [ ] Remove "Waiting" from JaaS interstitials
- [ ] Fix adding new cloud credentials flow in JaaS flow
- [ ] Verify KITT bar animation on all interstitials
- [ ] Debug error on kubes bundle in JaaS flow

**Comment by battlemidget** [comment]
@johnsca that spell error didn't surface running outside the snap, going to re-test that shortly

**Comment by mikemccracken** [comment]
The code changes look good, and login/deploy worked for me with JAAS and gcloud. +1 to merge this now and make smaller PRs with any tweaks

**Pull request merged**
